apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.1.2
  nodeSets:
  - name: balancer-nodes
    count: 1
    config:
      node.roles: []
      node.store.allow_mmap: false
    podTemplate:
      spec:
        nodeSelector:
          elastic: eck
        affinity: {}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: pagopa-d-weu-elk-elastic-aks-storage-hot
  - name: master-nodes
    count: 1
    config:
      node.roles: ["master"]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        nodeSelector:
          elastic: eck
        affinity: {}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: pagopa-d-weu-elk-elastic-aks-storage-hot
  - name: hot-nodes
    count: 1
    config:
      node.roles: ["ingest","data_content","data_hot"]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        nodeSelector:
          elastic: eck
        affinity: {}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: pagopa-d-weu-elk-elastic-aks-storage-hot
  - name: data-warm-nodes
    count: 1
    config:
      node.roles: ["ingest","data_warm"]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        nodeSelector:
          elastic: eck
        affinity: {}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: pagopa-d-weu-elk-elastic-aks-storage-warm
  - name: data-cold-nodes
    count: 1
    config:
      node.roles: ["data_cold","transform"]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        nodeSelector:
          elastic: eck
        affinity: {}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: pagopa-d-weu-elk-elastic-aks-storage-cold