version: '3.8'
services:
  db-nodo:
    image: postgres:15
    restart: always
    env_file:
      - ./dev.env
    ports:
      - '5432:5432'
    volumes:
      - db-nodo-data:/var/lib/postgresql/data
      - ./postgres-scripts/100-nodo-create-local.sh:/docker-entrypoint-initdb.d/100-nodo-create.sh
    networks:
      - db-nodo-net

volumes:
  db-nodo-data:

networks:
  db-nodo-net:
