apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connector-configuration-role
  namespace: ${namespace}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["debezium-secret", "registry-credential"]
    verbs: ["get"]
