apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 1m
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  creationTimestamp: "2024-12-06T08:55:55Z"
  generation: 1
  labels:
    ingress: debezium
  name: debezium-ingress
  namespace: gps
spec:
  ingressClassName: nginx
  rules:
    - host: weudev.gps.internal.dev.platform.pagopa.it
      http:
        paths:
          - backend:
              service:
                name: debezium-connect-cluster-connect-api
                port:
                  number: 8083
            path: /debezium/(.*)
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - weudev.gps.internal.dev.platform.pagopa.it
      secretName: weudev-gps-internal-dev-platform-pagopa-it
