# only manual
trigger: none
pr: none

parameters:
  - name: 'DEV'
    displayName: 'Plan on DEV environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'UAT'
    displayName: 'Plan on UAT environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'PROD'
    displayName: 'Plan on PROD environment'
    type: boolean
    default: True
    values:
      - False
      - True

variables:
  TIME_OUT: 10

pool:
  vmImage: 'ubuntu-20.04'

resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v3.0.0
      endpoint: 'io-azure-devops-github-ro'

lockBehavior: sequential
stages:
  - ${{ if eq(parameters['DEV'], true) }}:
    # DEV CORE
    - template: templates/terraform-plan-apply/template.yaml@terraform
      parameters:
        DOMAIN_NAME: 'core'
        AZURE_DEVOPS_POOL_AGENT_NAME: "pagopa-dev-linux-infra"
        ENVIRONMENT: "dev"
        TF_ENVIRONMENT_FOLDER: "dev"
        WORKINGDIR: 'src/core'
        AZURE_SERVICE_CONNECTION_NAME: DEV-PAGOPA-SERVICE-CONN

  #
  # UAT
  #
  - ${{ if eq(parameters['UAT'], true) }}:
    # UAT CORE
    - template: templates/terraform-plan-apply/template.yaml@terraform
      parameters:
        DOMAIN_NAME: 'core'
        AZURE_DEVOPS_POOL_AGENT_NAME: "pagopa-uat-linux"
        ENVIRONMENT: "uat"
        TF_ENVIRONMENT_FOLDER: "uat"
        WORKINGDIR: 'src/core'
        AZURE_SERVICE_CONNECTION_NAME: UAT-PAGOPA-SERVICE-CONN

  #
  # PROD
  #
  - ${{ if eq(parameters['PROD'], true) }}:
    # PROD CORE
    - template: templates/terraform-plan-apply/template.yaml@terraform
      parameters:
        DOMAIN_NAME: 'core'
        AZURE_DEVOPS_POOL_AGENT_NAME: "pagopa-prod-linux"
        ENVIRONMENT: "prod"
        TF_ENVIRONMENT_FOLDER: "prod"
        WORKINGDIR: 'src/core'
        AZURE_SERVICE_CONNECTION_NAME: PROD-PAGOPA-SERVICE-CONN
