# only manual
trigger: none
pr: none

parameters:
  - name: 'DEV'
    displayName: 'Run on DEV environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'UAT'
    displayName: 'Run on UAT environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'PROD'
    displayName: 'Run on PROD environment'
    type: boolean
    default: True
    values:
      - False
      - True

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v5.2.1
      endpoint: "io-azure-devops-github-ro"

variables:
  TIME_OUT: 30
  # working dir
  WORKING_DIR: 'src/elk-monitoring'
  DOMAIN_NAME: elk-monitoring

stages:
  #DEV
  - ${{ if eq(parameters['DEV'], true) }}:
    - template: './base-deploy-pipelines.yml'
      parameters:
        ENV: 'dev'
        ENV_FOLDER: 'dev'
        WORKING_DIR_MODULE: ${{ variables.WORKING_DIR }}
        DEFINITION_NAME: ${{ variables.DOMAIN_NAME }}
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_DEV)'
        SC_APPLY_NAME: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_DEV)'
        POOL_NAME: '$(TF_POOL_NAME_DEV)'
  #UAT
  - ${{ if eq(parameters['UAT'], true) }}:
    - template: './base-deploy-pipelines.yml'
      parameters:
        ENV: 'uat'
        ENV_FOLDER: 'uat'
        WORKING_DIR_MODULE: ${{ variables.WORKING_DIR }}
        DEFINITION_NAME: ${{ variables.DOMAIN_NAME }}
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_UAT)'
        SC_APPLY_NAME: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_UAT)'
        POOL_NAME: '$(TF_POOL_NAME_UAT)'
  #PROD
  - ${{ if eq(parameters['PROD'], true) }}:
    - template: './base-deploy-pipelines.yml'
      parameters:
        ENV: 'prod'
        ENV_FOLDER: 'prod'
        WORKING_DIR_MODULE: ${{ variables.WORKING_DIR }}
        DEFINITION_NAME: ${{ variables.DOMAIN_NAME }}
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_PROD)'
        SC_APPLY_NAME: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_PROD)'
        POOL_NAME: '$(TF_POOL_NAME_PROD)'
