# only manual
trigger: none
pr: none

parameters:
  - name: 'DEV'
    displayName: 'Run on DEV environment'
    type: boolean
    default: True
    values:
      - False
      - True


variables:
  TIME_OUT: 10
  # working dir
  WORKING_DIR: 'src'
  poolNameDev: '$(TF_POOL_NAME_DEV)'
#  poolNameUat: '$(TF_POOL_NAME_UAT)'
#  poolNameProd: '$(TF_POOL_NAME_PROD)'
  #APPLY
  azureServiceConnectionApplyNameDev: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_DEV)'
#  azureServiceConnectionApplyNameUat: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_UAT)'
#  azureServiceConnectionApplyNameProd: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_PROD)'
  APPROVE_NOTIFY_ADMIN: '[pagoPA-iac]\Project Administrators'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v6.1.0
      endpoint: "io-azure-devops-github-ro"


stages:
  - stage: DEV
    displayName: Nodo switch DEV
    dependsOn: []
    condition: and(succeeded(), eq(${{parameters.DEV}}, true))
    pool:
      name: "${{variables.poolNameDev}}"
    jobs:
      - job: waitForValidation
        condition: succeeded()
        displayName: Wait for external validation
        pool: server
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 240 # task times out in 4 hours
            inputs:
              notifyUsers: |
                $(APPROVE_NOTIFY_ADMIN)
              instructions: 'Please authorize the nodo switch and resume'
              onTimeout: 'reject'

