pr: none
trigger: none
#trigger:
#  - develop

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: k8sEnv
    displayName: K8s Environment
    type: string
    default: dev
    values:
      - dev
      - uat
      - prd

variables:
  - name: DEV_AZURE_SERVICE_CONNECTION
    value: '$(TF_DEV_AZURE_SERVICE_CONNECTION)'
  - name: UAT_AZURE_SERVICE_CONNECTION
    value: '$(TF_UAT_AZURE_SERVICE_CONNECTION)'
  - name: PRD_AZURE_SERVICE_CONNECTION
    value: '$(TF_PROD_AZURE_SERVICE_CONNECTION)'
  - name: ADMIN_USERNAME
    value: azureuser
  - name: DATABASE_NAME
    value: nodo
  - name: CFG_USERNAME
    value: cfg
  - name: CFG_SCHEMA
    value: cfg
  - name: OFFLINE_USERNAME
    value: offline
  - name: OFFLINE_SCHEMA
    value: offline
  - name: ONLINE_USERNAME
    value: online
  - name: ONLINE_SCHEMA
    value: online
  - name: RE_USERNAME
    value: re
  - name: RE_SCHEMA
    value: re
  - name: WFESP_USERNAME
    value: wfesp
  - name: WFESP_SCHEMA
    value: wfesp
  - name: DB-HOST-DEV
    value: pagopa-d-weu-nodo-flexible-postgresql-2
  - name: DB-HOST-UAT
    value: pagopa-u-weu-nodo-flexible-postgresql-2
  - name: DB-HOST-PRD
    value: pagopa-p-weu-nodo-flexible-postgresql-2

stages:
  ## GET INFO
  - stage: get_info
    displayName: "Initialization"
    jobs:
      - job: initialization
        displayName: "Init DB Nodo"
        steps:
          - ${{ if eq(parameters.k8sEnv, 'dev') }}:
              - task: AzureKeyVault@2
                displayName: "Get dev secrets"
                inputs:
                  azureSubscription: $(DEV_AZURE_SERVICE_CONNECTION)
                  keyVaultName: 'pagopa-d-nodo-kv'
                  secretsFilter: '*'
                  runAsPreJob: true
          - ${{ elseif eq(parameters.k8sEnv, 'uat') }}:
              - task: AzureKeyVault@2
                displayName: "Get uat secrets"
                inputs:
                  azureSubscription: 'UAT-pagoPA'
                  keyVaultName: 'pagopa-u-nodo-kv'
                  secretsFilter: '*'
                  runAsPreJob: true
          - ${{ elseif eq(parameters.k8sEnv, 'prd') }}:
              - task: AzureKeyVault@2
                displayName: "Get prd secrets"
                inputs:
                  azureSubscription: 'PRD-pagoPA'
                  keyVaultName: 'pagopa-p-nodo-kv'
                  secretsFilter: '*'
                  runAsPreJob: true
          - ${{ if eq(parameters.k8sEnv, 'dev') }}:
              - script:
                  echo "##vso[task.setvariable variable=DB-HOST;]$(DB-HOST-DEV)"
          - ${{ elseif eq(parameters.k8sEnv, 'uat') }}:
              - script:
                  echo "##vso[task.setvariable variable=DB-HOST;]$(DB-HOST-UAT)"
          - ${{ elseif eq(parameters.k8sEnv, 'prd') }}:
              - script:
                  echo "##vso[task.setvariable variable=DB-HOST;]$(DB-HOST-PRD)"
          - task: AzureCLI@2
            displayName: "cfg schema"
            inputs:
              azureSubscription: $(DEV_AZURE_SERVICE_CONNECTION)
              scriptLocation: inlineScript
              scriptType: bash
              inlineScript: |
                az config set extension.use_dynamic_install=yes_without_prompt
                az postgres flexible-server execute --name $(DB-HOST) --admin-user $(ADMIN_USERNAME) \
                --admin-password '$(db-administrator-login-password)' --database-name $(DATABASE_NAME) \
                --querytext "
                do \$\$
                BEGIN
                  IF EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$CFG_USERNAME') THEN
                    RAISE NOTICE 'Role "$CFG_USERNAME" already exists. Skipping.';
                  ELSE
                    CREATE ROLE $CFG_USERNAME LOGIN PASSWORD '$(db-cfg-password)';
                    GRANT ALL PRIVILEGES ON DATABASE "$DATABASE_NAME" TO $CFG_USERNAME;
                    GRANT $CFG_USERNAME to $ADMIN_USERNAME;
                    CREATE SCHEMA IF NOT EXISTS $CFG_SCHEMA AUTHORIZATION $CFG_USERNAME;
                  END IF;
                END
                \$\$;
                "
          - task: AzureCLI@2
            displayName: "online schema"
            inputs:
              azureSubscription: $(DEV_AZURE_SERVICE_CONNECTION)
              scriptLocation: inlineScript
              scriptType: bash
              inlineScript: |
                az config set extension.use_dynamic_install=yes_without_prompt
                az postgres flexible-server execute --name $(DB-HOST) --admin-user $(ADMIN_USERNAME) \
                --admin-password '$(db-administrator-login-password)' --database-name $(DATABASE_NAME) \
                --querytext "
                do \$\$
                BEGIN
                  IF EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$ONLINE_USERNAME') THEN
                    RAISE NOTICE 'Role "$ONLINE_USERNAME" already exists. Skipping.';
                  ELSE
                    CREATE ROLE $ONLINE_USERNAME LOGIN PASSWORD '$(db-online-password)';
                    GRANT ALL PRIVILEGES ON DATABASE "$DATABASE_NAME" TO $ONLINE_USERNAME;
                    GRANT $ONLINE_USERNAME to $ADMIN_USERNAME;
                    CREATE SCHEMA IF NOT EXISTS $ONLINE_SCHEMA AUTHORIZATION $ONLINE_USERNAME;
                  END IF;

                  CREATE or REPLACE FUNCTION trunc(timestamp without time zone) RETURNS date
                    AS 'select DATE_TRUNC(''day'',\$1);'
                    LANGUAGE SQL
                    IMMUTABLE
                    RETURNS NULL ON NULL INPUT;
                END
                \$\$;
                "
          - task: AzureCLI@2
            displayName: "offline schema"
            inputs:
              azureSubscription: $(DEV_AZURE_SERVICE_CONNECTION)
              scriptLocation: inlineScript
              scriptType: bash
              inlineScript: |
                az config set extension.use_dynamic_install=yes_without_prompt
                az postgres flexible-server execute --name $(DB-HOST) --admin-user $(ADMIN_USERNAME) \
                --admin-password '$(db-administrator-login-password)' --database-name $(DATABASE_NAME) \
                --querytext "
                do \$\$
                BEGIN
                  IF EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$OFFLINE_USERNAME') THEN
                    RAISE NOTICE 'Role "$OFFLINE_USERNAME" already exists. Skipping.';
                  ELSE
                    CREATE ROLE $OFFLINE_USERNAME LOGIN PASSWORD '$(db-offline-password)';
                    GRANT ALL PRIVILEGES ON DATABASE "$DATABASE_NAME" TO $OFFLINE_USERNAME;
                    GRANT $OFFLINE_USERNAME to $ADMIN_USERNAME;
                    CREATE SCHEMA IF NOT EXISTS $OFFLINE_SCHEMA AUTHORIZATION $OFFLINE_USERNAME;
                  END IF;
                END
                \$\$;
                "
          - task: AzureCLI@2
            displayName: "re schema"
            inputs:
              azureSubscription: $(DEV_AZURE_SERVICE_CONNECTION)
              scriptLocation: inlineScript
              scriptType: bash
              inlineScript: |
                az config set extension.use_dynamic_install=yes_without_prompt
                az postgres flexible-server execute --name $(DB-HOST) --admin-user $(ADMIN_USERNAME) \
                --admin-password '$(db-administrator-login-password)' --database-name $(DATABASE_NAME) \
                --querytext "
                do \$\$
                BEGIN
                  IF EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$RE_USERNAME') THEN
                    RAISE NOTICE 'Role "$RE_USERNAME" already exists. Skipping.';
                  ELSE
                    CREATE ROLE $RE_USERNAME LOGIN PASSWORD '$(db-re-password)';
                    GRANT ALL PRIVILEGES ON DATABASE "$DATABASE_NAME" TO $RE_USERNAME;
                    GRANT $RE_USERNAME to $ADMIN_USERNAME;
                    CREATE SCHEMA IF NOT EXISTS $RE_SCHEMA AUTHORIZATION $RE_USERNAME;
                  END IF;
                END
                \$\$;
                "
          - task: AzureCLI@2
            displayName: "wfesp schema"
            inputs:
              azureSubscription: $(DEV_AZURE_SERVICE_CONNECTION)
              scriptLocation: inlineScript
              scriptType: bash
              inlineScript: |
                az config set extension.use_dynamic_install=yes_without_prompt
                az postgres flexible-server execute --name $(DB-HOST) --admin-user $(ADMIN_USERNAME) \
                --admin-password '$(db-administrator-login-password)' --database-name $(DATABASE_NAME) \
                --querytext "
                do \$\$
                BEGIN
                  IF EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$WFESP_USERNAME') THEN
                    RAISE NOTICE 'Role "$WFESP_USERNAME" already exists. Skipping.';
                  ELSE
                    CREATE ROLE $WFESP_USERNAME LOGIN PASSWORD '$(db-wfesp-password)';
                    GRANT ALL PRIVILEGES ON DATABASE "$DATABASE_NAME" TO $WFESP_USERNAME;
                    GRANT $WFESP_USERNAME to $ADMIN_USERNAME;
                    CREATE SCHEMA IF NOT EXISTS $WFESP_SCHEMA AUTHORIZATION $WFESP_USERNAME;
                  END IF;
                END
                \$\$;
                "
