pr: none
trigger: none
#trigger:
#  - develop

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: k8sEnv
    displayName: K8s Environment
    type: string
    default: dev
    values:
      - dev
      - uat
      - prd

variables:
  - name: DEV_AZURE_SERVICE_CONNECTION
    value: '$(TF_DEV_AZURE_SERVICE_CONNECTION)'
  - name: UAT_AZURE_SERVICE_CONNECTION
    value: '$(TF_UAT_AZURE_SERVICE_CONNECTION)'
  - name: PRD_AZURE_SERVICE_CONNECTION
    value: '$(TF_PROD_AZURE_SERVICE_CONNECTION)'
  - name: POSTGRES_USER
    value: azureuser
  - name: POSTGRES_DB
    value: nodo
  - name: CFG_USERNAME
    value: cfg
  - name: CFG_SCHEMA
    value: cfg
  - name: OFFLINE_USERNAME
    value: offline
  - name: OFFLINE_SCHEMA
    value: offline
  - name: ONLINE_USERNAME
    value: online
  - name: ONLINE_SCHEMA
    value: online
  - name: RE_USERNAME
    value: re
  - name: RE_SCHEMA
    value: re
  - name: WFESP_USERNAME
    value: wfesp
  - name: WFESP_SCHEMA
    value: wfesp
  - name: host-dev
    value: pagopa-d-weu-nodo-flexible-postgresql-2
  - name: host-uat
    value: pagopa-d-weu-nodo-flexible-postgresql-2
  - name: host-prd
    value: pagopa-d-weu-nodo-flexible-postgresql-2

stages:
  ## GET INFO
  - stage: get_info
    displayName: "Initialization"
    jobs:
      - job: initialization
        displayName: "Init DB Nodo"
        steps:
          - ${{ if eq(parameters.k8sEnv, 'dev') }}:
              - task: AzureKeyVault@2
                displayName: "Get dev secrets"
                inputs:
                  azureSubscription: $(DEV_AZURE_SERVICE_CONNECTION)
                  keyVaultName: 'pagopa-d-nodo-kv'
                  secretsFilter: '*'
                  runAsPreJob: true
          - ${{ elseif eq(parameters.k8sEnv, 'uat') }}:
              - task: AzureKeyVault@2
                displayName: "Get uat secrets"
                inputs:
                  azureSubscription: 'UAT-pagoPA'
                  keyVaultName: 'pagopa-u-nodo-kv'
                  secretsFilter: '*'
                  runAsPreJob: true
          - ${{ elseif eq(parameters.k8sEnv, 'prd') }}:
              - task: AzureKeyVault@2
                displayName: "Get prd secrets"
                inputs:
                  azureSubscription: 'PRD-pagoPA'
                  keyVaultName: 'pagopa-p-nodo-kv'
                  secretsFilter: '*'
                  runAsPreJob: true
          - ${{ if eq(parameters.k8sEnv, 'dev') }}:
              - script:
                  echo "##vso[task.setvariable variable=HOST;]$(host-dev)"
          - ${{ elseif eq(parameters.k8sEnv, 'uat') }}:
              - script:
                  echo "##vso[task.setvariable variable=HOST;]$(host-uat)"
          - ${{ elseif eq(parameters.k8sEnv, 'prd') }}:
              - script:
                  echo "##vso[task.setvariable variable=HOST;]$(host-prd)"
          - task: AzureCLI@2
            displayName: "Azure CLI DB Nodo cfg"
            inputs:
              azureSubscription: $(DEV_AZURE_SERVICE_CONNECTION)
              scriptLocation: inlineScript
              scriptType: bash
              inlineScript: |
                az config set extension.use_dynamic_install=yes_without_prompt
                az postgres flexible-server execute --name $(HOST) --admin-user $(POSTGRES_USER) \
                --admin-password '$(db-administrator-login-password)'  --database-name $(POSTGRES_DB) \
                --querytext "
                do \$\$
                BEGIN
                  IF EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$CFG_USERNAME') THEN
                    RAISE NOTICE 'Role "$CFG_USERNAME" already exists. Skipping.';
                  ELSE
                    CREATE ROLE $CFG_USERNAME LOGIN PASSWORD '$CFG_PASSWORD';
                    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO $CFG_USERNAME;
                    GRANT $CFG_USERNAME to $POSTGRES_USER;
                    CREATE SCHEMA IF NOT EXISTS $CFG_SCHEMA AUTHORIZATION $CFG_USERNAME;
                  END IF;
                END
                \$\$;
                "
