namespace: "apiconfig"
nameOverride: ""
fullnameOverride: ""

deployment:
  create: true

kvCertificatesName:
  - weudev-apiconfig-internal-dev-platform-pagopa-it

keyvault:
  name: "pagopa-d-apiconfig-kv"
  tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
