namespace: "apiconfig"
nameOverride: ""
fullnameOverride: ""

deployment:
  create: true

kvCertificatesName:
  - weuuat-apiconfig-internal-uat-platform-pagopa-it

keyvault:
  name: "pagopa-u-apiconfig-kv"
  tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
