name: Static Analysis PR

on:
  push:
    branches-ignore:
      - main

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - run: |
          rm -rf *

      - name: 🔨 Get Modified Paths
        id: get-paths
        uses: pagopa/eng-github-actions-iac-template/global/get-modifed-folders@PAYMCLOUD-101-change-sparse-chackuot-module-nomencalture
        with:
          start_folder: "src"
          default_end_folder_depth: 3
          include_patterns: "src,domains"

      - name: 👀 See folders downloaded
        if: env.dir_changes_detected == 'true'
        id: see
        shell: bash
        run: |
          ls -la
          du -h -d 3 .

      - name: Static Analysis
        if: env.dir_changes_detected == 'true'
        uses: pagopa/eng-github-actions-iac-template/azure/terraform-static-analysis@v1.14.1
        with:
          precommit_version: 'v1.89.1@sha256:1ea921bc4fe87651d41677218e537afdcdb8202e757e554b9866668eaba144c5'
