name: Static Analysis PR

on:
  push:
    branches-ignore:
      - main

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - run: |
          rm -rf *

      - name: Checkout Modified Paths
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github

      - run: |
          ls -la
          pwd
          ls -la ./.github/actions

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Modified Paths
        id: get-paths
        run: |
          echo "get current branch"
          current_branch=${GITHUB_HEAD_REF}
          echo "get modified paths from source"
          modified_paths_source=$(git diff --name-only $current_branch origin/main | grep -v 'domains' | grep '/' | cut -d '/' -f 1,2 | uniq )
          echo "$modified_paths_source"
          echo "get modified paths from domains"
          modified_paths_domains=$(git diff --name-only $current_branch origin/main | grep 'domains' | grep '/' | cut -d '/' -f 1,2,3 | uniq )
          echo "$modified_paths_domains"
          echo "merge paths"
          modified_paths="$modified_paths_source $modified_paths_domains .github"
          variabile_multiline=$(echo "$modified_paths" | tr ' ' '\n')
          echo "📌 modified_paths"
          echo "$modified_paths" > "/tmp/paths.txt"
        shell: bash

      - name: 👀 See folders downloaded
        id: download
        shell: bash
        run: |
          PAGOPA_MULTIPLE_FOLDERS=$(fold -w $(wc -L < "/tmp/paths.txt") < "/tmp/paths.txt")
          echo $PAGOPA_MULTIPLE_FOLDERS
          git sparse-checkout init --cone
          git sparse-checkout set $PAGOPA_MULTIPLE_FOLDERS
          git checkout

#      - name: Checkout Modified Paths
#        uses: actions/checkout@v4
#        with:
#          sparse-checkout: |
#            $(fold -w $(wc -L < "/tmp/paths.txt") < "/tmp/paths.txt")

      - name: See folders downloaded
        id: see
        shell: bash
        run: |
          ls -la
          du -h -d 3 .

      - name: Static Analysis
        uses: pagopa/eng-github-actions-iac-template/azure/terraform-static-analysis@v1.14.1
        with:
          precommit_version: 'v1.89.1@sha256:1ea921bc4fe87651d41677218e537afdcdb8202e757e554b9866668eaba144c5'


