name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches-ignore:
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '.**'

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: init
        run: |
          cd src
          sed -i -e 's/backend "azurerm" {}//g' main.tf
          docker run -v $(pwd):/tmp hashicorp/terraform:latest init

      - name: test
        run: |
          TAG=latest
          docker run -v $(pwd):/lint -w /lint ghcr.io/antonbabenko/pre-commit-terraform:$TAG run -a
