name: Static Analysis PR

on:
  push:
    branches-ignore:
      - main

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Modified Paths
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github

      - run: |
          ls -la
          pwd
          ls -la ./.github/actions

      - name: Checkout Modified Paths
        uses: ./.github/actions/checkout-modified-paths
