name: Static Analysis PR

on:
  push:
    branches-ignore:
      - main

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Modified Paths
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github

      - run: |
          ls -la
          pwd
          ls -la ./.github/actions

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Modified Paths
        id: get-paths
        run: |
          echo "get current branch"
          current_branch=${GITHUB_HEAD_REF}
          echo "get modified paths from source"
          modified_paths_source=$(git diff --name-only $current_branch origin/main | grep -v 'domains' | grep '/' | cut -d '/' -f 1,2 | uniq )
          echo "$modified_paths_source"
          echo "get modified paths from domains"
          modified_paths_domains=$(git diff --name-only $current_branch origin/main | grep 'domains' | grep '/' | cut -d '/' -f 1,2,3 | uniq )
          echo "$modified_paths_domains"
          echo "merge paths"
          modified_paths="$modified_paths_source $modified_paths_domains .github"
          variabile_multiline=$(echo "$modified_paths" | tr ' ' '\n')

          echo "PAGOPA_MULTIPLE_FOLDERS=${variabile_multiline| base64}" >> "$GITHUB_ENV"
        shell: bash

      - name: See folders downloaded
        id: download
        shell: bash
        run: |
          echo "${PAGOPA_MULTIPLE_FOLDERS | base64 -d}"
          for path in ${PAGOPA_MULTIPLE_FOLDERS| base64 -d}; do
            git checkout "$path"

            echo "Checkout eseguito in: $path"
          done

#      - name: Checkout Modified Paths
#        uses: actions/checkout@v4
#        with:
#          sparse-checkout: ${{ steps.get-paths.outputs.paths }}

      - name: See folders downloaded
        id: see
        shell: bash
        run: |
          ls -la
          du -h -d 3 .


