name: Static Analysis PR

on:
  push:
    branches-ignore:
      - main

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Clean workspace
        run: |
          rm -rf *

      - name: Checkout Modified Paths
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github

      - run: |
          ls -la
          pwd
          ls -la ./.github/actions

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Modified Paths
        id: get-paths
        run: |
          # Ottieni il nome del branch corrente
          current_branch=${GITHUB_HEAD_REF}

          # Ottieni il commit di origine del branch corrente
          base_commit=$(git rev-parse $current_branch^1)

          # Ottieni i percorsi modificati rispetto al commit di origine del branch
          modified_paths_source=$(git diff --name-only $base_commit | grep -v 'domains' | grep '/' | cut -d '/' -f 1,2 | uniq)
          echo "$modified_paths_source"

          modified_paths_domains=$(git diff --name-only $base_commit | grep 'domains' | grep '/' | cut -d '/' -f 1,2,3 | uniq)
          echo "$modified_paths_domains"

          # Unisci i percorsi modificati e aggiungi il percorso ".github"
          modified_paths="$modified_paths_source $modified_paths_domains .github"

          echo "📌 modified_paths"
          echo "$modified_paths" > "/tmp/paths.txt"
        shell: bash

      - name: 👀 See folders downloaded
        id: download
        shell: bash
        run: |
          cat /tmp/paths.txt
          PAGOPA_MULTIPLE_FOLDERS=$(fold -w $(wc -L < "/tmp/paths.txt") < "/tmp/paths.txt")
          echo $PAGOPA_MULTIPLE_FOLDERS
          git sparse-checkout init --cone
          git sparse-checkout set $PAGOPA_MULTIPLE_FOLDERS
          git checkout

#      - name: Checkout Modified Paths
#        uses: actions/checkout@v4
#        with:
#          sparse-checkout: |
#            $(fold -w $(wc -L < "/tmp/paths.txt") < "/tmp/paths.txt")

      - name: See folders downloaded
        id: see
        shell: bash
        run: |
          ls -la
          du -h -d 3 .

      # - name: Static Analysis
      #   uses: pagopa/eng-github-actions-iac-template/azure/terraform-static-analysis@v1.14.1
      #   with:
      #     precommit_version: 'v1.89.1@sha256:1ea921bc4fe87651d41677218e537afdcdb8202e757e554b9866668eaba144c5'


