name: Docker

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - 'CODEOWNERS'

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: init_src
        run: |
          cd src
          sed -i -e 's/backend "azurerm" {}//g' main.tf # use local backend
          TAG=latest
          docker run -v $(pwd):/tmp -w /tmp hashicorp/terraform:$TAG init

      - name: run_test
        run: |
          TAG=latest
          docker run -v $(pwd):/lint -w /lint ghcr.io/antonbabenko/pre-commit-terraform:$TAG run -a
