name: Static Analysis PR

on:
  push:
    branches-ignore:
      - main

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Modified Paths
        uses: ./.github/actions/checkout-modified-paths.yml
